/*var currentColor = undefined;
$(".small").click(function(event) {
$(".small").removeClass('border')
currentColor = $(this).text()
$(this).addClass('border');
});
$(".big").click(function(event){
	if($(this).hasClass(currentColor)){
		alert("Есть")
	}
});*/

// $("div").click(function(event){
// 	$(this)
// 	.text(
// 		$(this).width()
// 		)
// });

// $("div").click(function(event){
// 	$(this)
// 	.height(25)
// 	.width(25)
		
// });